Repository JNU-econovation/ReRe, pull requests merged in 2024-01, with the labels that each got.

#19 [BE/FEAT] JPA Entity 작성
  BE/.gradle/8.5/checksums/checksums.lock
  BE/.gradle/8.5/dependencies-accessors/dependencies-accessors.lock
  BE/.gradle/8.5/dependencies-accessors/gc.properties
  BE/.gradle/8.5/executionHistory/executionHistory.lock
  BE/.gradle/8.5/fileChanges/last-build.bin
  BE/.gradle/8.5/fileHashes/fileHashes.lock
  BE/.gradle/8.5/gc.properties
  BE/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  BE/.gradle/buildOutputCleanup/cache.properties
  BE/.gradle/vcs-1/gc.properties
  BE/.idea/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/gradle.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/misc.xml
  BE/.idea/uiDesigner.xml
  BE/.idea/vcs.xml
  BE/src/main/java/com/econovation/rere/entity/BlindCard.java
  BE/src/main/java/com/econovation/rere/entity/Card.java
  BE/src/main/java/com/econovation/rere/entity/CardBook.java
  BE/src/main/java/com/econovation/rere/entity/Session.java
  BE/src/main/java/com/econovation/rere/entity/StudyComplete.java
  BE/src/main/java/com/econovation/rere/entity/Theme.java
  BE/src/main/java/com/econovation/rere/entity/User.java
  BE/src/main/resources/application.properties
Labels: Feature 💻, BE

#21 [BE/FEAT] Request/Response DTO 작성
  .gitignore
  BE/.gradle/8.5/checksums/checksums.lock
  BE/.gradle/8.5/checksums/md5-checksums.bin
  BE/.gradle/8.5/checksums/sha1-checksums.bin
  BE/.idea/modules.xml
  BE/build.gradle
  BE/src/main/java/com/econovation/rere/domain/dto/request/BlindCardCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/UserCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/UserLoginRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/CardBookResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/CardResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/ThemeResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/UserLoginResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/entity/BlindCard.java
  BE/src/main/java/com/econovation/rere/domain/entity/Card.java
  BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java
  BE/src/main/java/com/econovation/rere/domain/entity/Session.java
  BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java
  BE/src/main/java/com/econovation/rere/domain/entity/Theme.java
  BE/src/main/java/com/econovation/rere/domain/entity/User.java
  BE/src/main/java/com/econovation/rere/domain/entity/UserCardBook.java
  BE/src/main/java/com/econovation/rere/domain/repository/BlindCardRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/CardBookRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/CardRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/StudyCompleteRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/ThemeRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/UserCardBookRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/UserRepository.java
  BE/src/main/java/com/econovation/rere/service/CardBookService.java
  BE/src/test/java/com/econovation/rere/repository/CardBookRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/CardRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/ThemeRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/UserCardBookRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/UserRepositoryTest.java
Labels: Feature 💻, BE

#23 [BE/FEAT] gitignore 재설정
  .gitignore
  BE/.idea/modules.xml
  BE/src/main/resources/application.properties
Labels: Document 📃, BE

#25 [BE/FEAT] Service 계층 구현 및 Entity 수정, DTO 생성
  BE/src/main/java/com/econovation/rere/domain/dto/request/BlindCardCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/UserCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/CardBookResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/CardResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/entity/BlindCard.java
  BE/src/main/java/com/econovation/rere/domain/entity/Card.java
  BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java
  BE/src/main/java/com/econovation/rere/domain/entity/Session.java
  BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java
  BE/src/main/java/com/econovation/rere/domain/entity/Theme.java
  BE/src/main/java/com/econovation/rere/domain/entity/User.java
  BE/src/main/java/com/econovation/rere/domain/entity/UserCardBook.java
  BE/src/main/java/com/econovation/rere/domain/repository/CardBookRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/CardRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/ThemeRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/UserCardBookRepository.java
  BE/src/main/java/com/econovation/rere/domain/repository/UserRepository.java
  BE/src/main/java/com/econovation/rere/service/CardBookService.java
  BE/src/main/java/com/econovation/rere/service/CardService.java
  BE/src/main/java/com/econovation/rere/service/ThemeService.java
  BE/src/main/java/com/econovation/rere/service/UserCardBookService.java
Labels: Feature 💻, BE

#33 [BE/FEAT] ThemeController 구현
  BE/src/main/java/com/econovation/rere/controller/ThemeController.java
Labels: Feature 💻, BE

#32 [BE/FEAT] CardController 구현
  BE/src/main/java/com/econovation/rere/controller/CardBookController.java
  BE/src/main/java/com/econovation/rere/controller/CardController.java
  BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java
  BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java
  BE/src/main/java/com/econovation/rere/domain/entity/User.java
  BE/src/main/java/com/econovation/rere/domain/entity/UserCardBook.java
  BE/src/main/java/com/econovation/rere/domain/repository/StudyCompleteRepository.java
  BE/src/main/java/com/econovation/rere/exception/StudyCompleteNotFoundException.java
  BE/src/main/java/com/econovation/rere/service/StudyService.java
  BE/src/test/java/com/econovation/rere/repository/UserRepositoryTest.java
Labels: Feature 💻, BE

#34 [BE/FEAT] API url 변경
  BE/src/main/java/com/econovation/rere/controller/UserController.java
Labels: Feature 💻, BE

#36 [BE/FEAT] cardbook Controller 구현 + 인증/인가 기능
  BE/build.gradle
  BE/src/main/java/com/econovation/rere/controller/CardBookController.java
  BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/BlindCardCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookRemoveRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeRemoveRequestDTO.java
  BE/src/main/java/com/econovation/rere/exception/NotAthenticationException.java
  BE/src/main/java/com/econovation/rere/service/CardBookService.java
  BE/src/main/resources/application-db.properties.properties
  BE/src/main/resources/application.properties
  BE/src/test/java/com/econovation/rere/repository/CardBookRepositoryTest.java
Labels: Feature 💻, BE

#40 [BE/FEAT] CardBook and Theme Controller Refactor
  BE/src/main/java/com/econovation/rere/config/WebConfig.java
  BE/src/main/java/com/econovation/rere/controller/CardBookController.java
  BE/src/main/java/com/econovation/rere/controller/ThemeController.java
  BE/src/main/java/com/econovation/rere/interceptor/LoginInterceptor.java
  BE/src/main/java/com/econovation/rere/service/UserCardBookService.java
  BE/src/main/resources/application.properties
Labels: Feature 💻, BE

#41 [BE/FEAT] StudyService refactoring
  BE/src/main/java/com/econovation/rere/config/WebConfig.java
  BE/src/main/java/com/econovation/rere/controller/CardBookController.java
  BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java
  BE/src/main/java/com/econovation/rere/controller/ThemeController.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/UserCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/ThemePageResponseDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/response/ThemeResponseDTO.java
  BE/src/main/java/com/econovation/rere/exception/DuplicateLoginIdException.java
  BE/src/main/java/com/econovation/rere/exception/DuplicateNicknameException.java
  BE/src/main/java/com/econovation/rere/service/ThemeService.java
  BE/src/main/java/com/econovation/rere/service/UserService.java
Labels: Feature 💻, BE

#43 [BE/FEAT] Soft Delete 구현
  BE/src/main/java/com/econovation/rere/controller/ThemeController.java
  BE/src/main/java/com/econovation/rere/domain/entity/BlindCard.java
  BE/src/main/java/com/econovation/rere/domain/entity/Card.java
  BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java
  BE/src/main/java/com/econovation/rere/domain/entity/StudyComplete.java
  BE/src/main/java/com/econovation/rere/domain/entity/Theme.java
  BE/src/main/java/com/econovation/rere/domain/entity/User.java
Labels: Feature 💻, BE

#47 [FE/FEAT] Page들 구현
  .gitignore
  FE/.eslintrc.cjs
  FE/.gitignore
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/public/1.png
  FE/public/2.png
  FE/public/3.png
  FE/public/4.png
  FE/public/bookImage.png
  FE/public/logo.png
  FE/public/macos-original-icon.png
  FE/public/vite.svg
  FE/src/App.jsx
  FE/src/components/card/CardTest.js
  FE/src/components/cardcreate/AddedCard.component.jsx
  FE/src/components/cardcreate/CardInput.component.jsx
  FE/src/components/common/Bar.component.jsx
  FE/src/components/common/Button.component.jsx
  FE/src/components/common/CardBook.component.jsx
  FE/src/components/common/Icon.component.jsx
  FE/src/components/common/Img.component.jsx
  FE/src/components/common/Modal.component.jsx
  FE/src/components/common/layout/Header.component.jsx
  FE/src/components/index/BlueBox.component.jsx
  FE/src/components/index/IndexGrid.component.jsx
  FE/src/components/index/IndexTest.js
  FE/src/components/index/NewBlueBox.component.jsx
  FE/src/components/main/Grid.component.jsx
  FE/src/components/main/MainBar.component.jsx
  FE/src/components/main/MainTest.js
  FE/src/components/main/NewCard.component.jsx
  FE/src/components/signup/Input.component.jsx
  FE/src/components/signup/InputDuplicate.component.jsx
  FE/src/main.jsx
  FE/src/pages/Card.page.jsx
  FE/src/pages/CardCreate.page.jsx
  FE/src/pages/Index.page.jsx
  FE/src/pages/Login.page.jsx
  FE/src/pages/Search.page.jsx
  FE/src/pages/main.page.jsx
  FE/src/pages/signup.page.jsx
  FE/src/styles/App.css
  FE/src/styles/CardStyle.css
  FE/src/styles/Container.jsx
  FE/src/styles/index.css
  FE/vite.config.js
Labels: Feature 💻, FE

#48 [BE/FEAT] 학습 알림 기능 구현
  BE/src/main/java/com/econovation/rere/Thread/StudyTimeCheckThread.java
  BE/src/main/java/com/econovation/rere/config/WebConfig.java
  BE/src/main/java/com/econovation/rere/controller/ServerSendEventController.java
  BE/src/main/java/com/econovation/rere/controller/ThemeController.java
  BE/src/main/java/com/econovation/rere/domain/repository/StudyCompleteRepository.java
  BE/src/main/java/com/econovation/rere/domain/sse/SseEmitters.java
  BE/src/main/java/com/econovation/rere/event/EventHandler.java
  BE/src/main/java/com/econovation/rere/event/StudyAlarmEvent.java
  BE/src/main/java/com/econovation/rere/event/StudyTimeCheck.java
  BE/src/main/java/com/econovation/rere/service/AlarmService.java
  BE/src/main/java/com/econovation/rere/service/StudyService.java
  BE/src/main/resources/application.properties
Labels: Feature 💻, BE

#57 [BE/FEAT] 배포 설정
  BE/src/main/java/com/econovation/rere/config/CurrentUserArgumentResolver.java
  BE/src/main/java/com/econovation/rere/config/WebConfig.java
  BE/src/main/java/com/econovation/rere/controller/CardBookController.java
  BE/src/main/java/com/econovation/rere/controller/CardController.java
  BE/src/main/java/com/econovation/rere/controller/GlobalExceptionHandler.java
  BE/src/main/java/com/econovation/rere/controller/ServerSendEventController.java
  BE/src/main/java/com/econovation/rere/controller/ThemeController.java
  BE/src/main/java/com/econovation/rere/controller/UserController.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookCreateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookRemoveRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/CardBookUpdateRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/dto/request/ThemeRemoveRequestDTO.java
  BE/src/main/java/com/econovation/rere/domain/entity/CardBook.java
  BE/src/main/java/com/econovation/rere/event/StudyTimeCheck.java
  BE/src/main/java/com/econovation/rere/exception/ImageNotLoadException.java
  BE/src/main/java/com/econovation/rere/service/CardBookService.java
  BE/src/main/java/com/econovation/rere/service/ThemeService.java
  BE/src/main/java/com/econovation/rere/service/UserService.java
  BE/src/main/java/com/econovation/rere/thread/StudyTimeCheckThread.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/econovation/rere/repository/CardBookRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/CardRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/ThemeRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/UserCardBookRepositoryTest.java
  BE/src/test/java/com/econovation/rere/repository/UserRepositoryTest.java
Labels: Feature 💻, BE

#58 [BE/FEAT] Cardbook Controller 로그 추가
  BE/src/main/java/com/econovation/rere/controller/CardBookController.java
Labels: Feature 💻, BE
